name: Android CI/CD

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: false
        type: string
  push:
    branches:
      - master-custom
    paths:
      - 'Android-kotlin-Code/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Android-kotlin-Code

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3.2.0
      with:
        log-accepted-android-sdk-licenses: false
        cmdline-tools-version: '12266719'
        packages: 'platforms;android-35 build-tools;35.0.0 platform-tools'

    - name: Setup Java
      uses: actions/setup-java@v4.7.0
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v3

    - name: Build debug APK
      run: ./gradlew assembleDebug

    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: Android-kotlin-Code/app/build/outputs/apk/alpha/debug/*.apk

    - name: Run tests
      run: ./gradlew test

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event.inputs.release_tag != ''
    defaults:
      run:
        working-directory: ./Android-kotlin-Code

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3.2.0
      with:
        log-accepted-android-sdk-licenses: false
        cmdline-tools-version: '12266719'
        packages: 'platforms;android-35 build-tools;35.0.0 platform-tools'

    - name: Setup Java
      uses: actions/setup-java@v4.7.0
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode keystore
      env:
        KEYSTORE: ${{ secrets.KEYSTORE }}
      run: |
        echo $KEYSTORE | base64 -d > release.keystore

    - name: Create signing.properties
      run: |
        echo "keystore.password=${{ secrets.KEYSTORE_PASSWORD }}" > signing.properties
        echo "key.alias=${{ secrets.KEY_ALIAS }}" >> signing.properties
        echo "key.password=${{ secrets.KEY_PASSWORD }}" >> signing.properties

    - name: Build release APK
      run: ./gradlew assembleRelease

    - name: Sign APK
      uses: ilharp/sign-android-release@v1
      id: sign_app
      with:
        releaseDir: Android-kotlin-Code/app/build/outputs/apk/alpha/release
        signingKey: release.keystore
        keyAlias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.release_tag }}
        release_name: Release ${{ github.event.inputs.release_tag }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.sign_app.outputs.signedFile }}
        asset_name: uuvpn-release.apk
        asset_content_type: application/vnd.android.package-archive